// Canonicalization table for the free-text "Organization/Institution" column
// in "Capacity Building on the Use of Oracle HyperionAttendance Registration
// Form(1-688).xlsx". That column was typed by ~555 different respondents, so
// the same MDA appears under many spellings/abbreviations/case variants.
//
// ALIASES maps a normalized (lowercased, whitespace-collapsed, trimmed) raw
// string to a canonical display name. Anything not listed here is used
// as-is (after light cleanup) as its own institution — this is deliberately
// not exhaustive, only entries with real ambiguity/duplication are listed.
//
// CANONICAL_META optionally overrides the institutionId (to reuse an
// existing institution already in Firestore instead of creating a
// duplicate) and/or the institutionType (default 'MDA') for a canonical
// name.
//
// Built by cross-referencing the 355 unique raw strings in the sheet
// against each other and against the ~290 institutions already in
// Firestore (scripts/institutions_dump.json, pulled 2026-09-17). Ghana MDA
// names/abbreviations resolved from general knowledge — verify anything
// that looks off before a production import.

function norm(s) {
  return String(s).toLowerCase().trim().replace(/\s+/g, ' ');
}

const RAW_ALIASES = {
  'ARCC': 'Ashanti Regional Coordinating Council',
  'Ashanti Regional Coordinating Council': 'Ashanti Regional Coordinating Council',
  'BNI': 'Bureau of National Investigations (BNI)',
  'CAGD': "Controller and Accountant General's Department",
  "Controller and Accountant General's Department": "Controller and Accountant General's Department",
  "CONTROLLER AND ACCOUNTANT GENERAL'S DEPARTMENT": "Controller and Accountant General's Department",
  'Controller and Accountant Generals Department': "Controller and Accountant General's Department",
  'CENDLOS': 'Centre for National Distance Learning and Open Schooling (CENDLOS)',
  'CENTER FOR NATIONAL DISTANCE LEARNING AND OPEN SCHOOLING (CENDLOS)': 'Centre for National Distance Learning and Open Schooling (CENDLOS)',
  'Central Regional Co-ordinating Council': 'Central Regional Coordinating Council',
  'CENTRAL REGIONAL COORDINATING COUNCIL': 'Central Regional Coordinating Council',
  'Centre for Plant Medicine Research': 'Centre for Plant Medicine Research',
  'Centre for Plant medicine Research': 'Centre for Plant Medicine Research',
  'CHAG': 'Christian Health Association of Ghana',
  'Christian Health Association of Ghana': 'Christian Health Association of Ghana',
  'CHRISTIAN HEALTH ASSOCIATION OF GHANA': 'Christian Health Association of Ghana',
  'MOH - CHAG': 'Christian Health Association of Ghana',
  'MOH-CHAG': 'Christian Health Association of Ghana',
  'CHRAJ': 'Commission on Human Rights and Administrative Justice',
  'Chraj': 'Commission on Human Rights and Administrative Justice',
  'Commission on Human Rights and Administrative Justice': 'Commission on Human Rights and Administrative Justice',
  'Christ the Teacher College of Education': 'Christ the Teacher College of Education',
  'Christ The Teacher College of Education': 'Christ the Teacher College of Education',
  'Community 22 Polyclinic ,Ashaiman': 'Community 22 Polyclinic, Ashaiman',
  'Community Water and Sanitation Agency': 'Community Water and Sanitation Agency',
  'Community water and sanitation agency': 'Community Water and Sanitation Agency',
  'Complementary Education Agency': 'Complementary Education Agency',
  'Council for Scientific and Industrial Research': 'Council for Scientific and Industrial Research (CSIR)',
  'Council for scientific and Industrial research': 'Council for Scientific and Industrial Research (CSIR)',
  'Council for Scientific and Industrial Research - Head Office': 'Council for Scientific and Industrial Research (CSIR)',
  'Council for Scientific and Industrial Research (CSIR)': 'Council for Scientific and Industrial Research (CSIR)',
  'CSIR': 'Council for Scientific and Industrial Research (CSIR)',
  'Csir': 'Council for Scientific and Industrial Research (CSIR)',
  'CSIR - Head office': 'Council for Scientific and Industrial Research (CSIR)',
  'CSIR, Head Office': 'Council for Scientific and Industrial Research (CSIR)',
  'Council of state': 'Council of State',
  'Creative arts agency': 'Creative Arts Agency',
  'CTVET': 'Ghana TVET Service',
  'CTVET-MOE': 'Ghana TVET Service',
  'Ghana TVET': 'Ghana TVET Service',
  'Ghana TVET Service': 'Ghana TVET Service',
  'GHANA TVET SERVICE': 'Ghana TVET Service',
  'Ghana TVET service': 'Ghana TVET Service',
  'Ghana Tvet Service': 'Ghana TVET Service',
  'GTVETS': 'Ghana TVET Service',
  'TVETS': 'Ghana TVET Service',
  'Cyber Security Authority': 'Cyber Security Authority',
  'CYBER SECURITY AUTHORITY': 'Cyber Security Authority',
  'Cyber security Authority': 'Cyber Security Authority',
  'Data Prootection Commission': 'Data Protection Commission',
  'DATA PROTECTION COMMISSION': 'Data Protection Commission',
  'Department of Co-operatives': 'Department of Co-operatives',
  'DEPARTMENT OF CO-OPERATIVES': 'Department of Co-operatives',
  'DEPARTMENT OF FACTORIES INSPECTORATE': 'Department of Factories Inspectorate',
  'DEPARTMENT OF SOCIAL WELFARE': 'Department of Social Welfare',
  'Diaspora Affairs Office': 'Diaspora Affairs Office',
  'Diaspora Affairs Office of the President': 'Diaspora Affairs Office',
  'EASTERN REGIONAL COORDINATING COUNCIL': 'Eastern Regional Coordinating Council',
  'Electrical and Electronic Waste Management Fund': 'Electrical and Electronic Waste Management Fund',
  'Ewaste Fund': 'Electrical and Electronic Waste Management Fund',
  'Energy Commission': 'Energy Commission',
  'Energy commission': 'Energy Commission',
  'Environmental Protection Agency': 'Environmental Protection Agency',
  'Environmental Protection Authority': 'Environmental Protection Agency',
  'Environmental Protection Authority Assistant Finance Officer': 'Environmental Protection Agency',
  'Fisheries Commission': 'Fisheries Commission',
  'FISHERIES COMMISSION': 'Fisheries Commission',
  'Fisheries commission': 'Fisheries Commission',
  'Forestry Commission FSD': 'Forestry Commission',
  'Forestry Commission, Wildlife Division': 'Forestry Commission',
  'Gaming Commission': 'Gaming Commission',
  'GAMING COMMISSION OF GHANA': 'Gaming Commission',
  'Gaming of Ghana': 'Gaming Commission',
  'GBC': 'Ghana Broadcasting Corporation',
  'Ghana Broadcasting Corporation': 'Ghana Broadcasting Corporation',
  'GES': 'Ghana Education Service',
  'Ghana Book Development Council': 'Ghana Book Development Council',
  'Ghana Book Development council': 'Ghana Book Development Council',
  'Ghana boundary commission': 'Ghana Boundary Commission',
  'Ghana Boundary Commission': 'Ghana Boundary Commission',
  'Ghana Commission for UNESCO': 'Ghana Commission for UNESCO',
  'GHANA COMMISSION FOR UNESCO': 'Ghana Commission for UNESCO',
  'Ghana Health Service': 'Ghana Health Service',
  'Ghana health service': 'Ghana Health Service',
  'Ghana Health Service HQ': 'Ghana Health Service',
  'Ghs': 'Ghana Health Service',
  'Ghana Health Service/ Achimota Hospital': 'Ghana Health Service - Achimota Hospital',
  'Ghana Health Service/Weija-Gbawe Municipal Hospital': 'Weija-Gbawe Municipal Hospital',
  'GHS/Weija-Gbawe Municipal Hospital': 'Weija-Gbawe Municipal Hospital',
  'Ghana Health WeijaGbawe hospt': 'Weija-Gbawe Municipal Hospital',
  'MOH weija Gbawe Municipal Hodpt': 'Weija-Gbawe Municipal Hospital',
  'Weija Gbawe Municipal Health Directorate': 'Weija-Gbawe Municipal Hospital',
  'Weija Gbawe Municipal Hospital': 'Weija-Gbawe Municipal Hospital',
  'GHANA HYDROLOGICAL AUTHORITY': 'Ghana Hydrological Authority',
  'Ghana International Trade Commission': 'Ghana International Trade Commission',
  'Ghana international trade commission': 'Ghana International Trade Commission',
  'GHANA INTERNATIONAL TRADE COMMISSION': 'Ghana International Trade Commission',
  'Ghana Meteorological Agenct': 'Ghana Meteorological Agency',
  'Ghana Museums and Monuments Board': 'Ghana Museums and Monuments Board',
  'GMMB': 'Ghana Museums and Monuments Board',
  'Ghana Muslim Mission College of Education': 'Ghana Muslim Mission College of Education',
  'Ghana Muslim Mission College of education': 'Ghana Muslim Mission College of Education',
  'Ghana National Fire Service': 'Ghana National Fire Service',
  'GNFS': 'Ghana National Fire Service',
  'Ghana News Agency': 'Ghana News Agency',
  'OGM/Ghana News Agency': 'Ghana News Agency',
  'OGM/GNA': 'Ghana News Agency',
  'Ghana Prisons Service': 'Ghana Prisons Service',
  'Ghana prisons service': 'Ghana Prisons Service',
  'Ghana Prsions Service': 'Ghana Prisons Service',
  'Ghanan Prisons service': 'Ghana Prisons Service',
  'Ghana school of survey and mapping': 'Ghana School of Survey and Mapping',
  'Ghana Standards Authority': 'Ghana Standards Authority',
  'MOTAI/Ghana Standards Authority': 'Ghana Standards Authority',
  'Ghana Statistical Service': 'Ghana Statistical Service',
  'Ghana statistical Service': 'Ghana Statistical Service',
  'Ghana Tourism Authority': 'Ghana Tourism Authority',
  'GHANA TOURISM AUTHORITY': 'Ghana Tourism Authority',
  'GI KACE': 'Ghana-India Kofi Annan Centre of Excellence in ICT (GI-KACE)',
  'GI-KACE': 'Ghana-India Kofi Annan Centre of Excellence in ICT (GI-KACE)',
  'Giadec': 'Ghana Integrated Aluminium Development Corporation (GIADEC)',
  'GIADEC': 'Ghana Integrated Aluminium Development Corporation (GIADEC)',
  'Government secretarial school': 'Government Secretarial School',
  'Gratis foundation': 'GRATIS Foundation',
  'GRATIS FOUNDATION': 'GRATIS Foundation',
  'GRATIS Foundation': 'GRATIS Foundation',
  'Greater Accra Regional Co-ordinating Council': 'Greater Accra Regional Coordinating Council',
  'GREATER ACCRA REGIONAL CORDINATING COUNCIL': 'Greater Accra Regional Coordinating Council',
  'GTEC': 'Ghana Tertiary Education Commission (GTEC)',
  'IAA': 'Internal Audit Agency',
  'Internal Audit Agency': 'Internal Audit Agency',
  'Institute of Accountancy': 'Institute of Accountancy Training',
  'Institute of Accountancy Training': 'Institute of Accountancy Training',
  'KBTH': 'Korle Bu Teaching Hospital',
  'KORLE BU TEACHING HOSPITAL': 'Korle Bu Teaching Hospital',
  'Korle Bu Teaching Hospital': 'Korle Bu Teaching Hospital',
  'Korle bu Teaching hospital': 'Korle Bu Teaching Hospital',
  'Lands and natural resources': 'Ministry of Lands and Natural Resources',
  'Ministry of Lands & Natural Resources': 'Ministry of Lands and Natural Resources',
  'Ministry of Lands and Natural Resources': 'Ministry of Lands and Natural Resources',
  'MLNR': 'Ministry of Lands and Natural Resources',
  'Management Development & Productivity Institute': 'Management Development and Productivity Institute',
  'Management Development and Productivity Institute': 'Management Development and Productivity Institute',
  'Management Development and productivity Institute': 'Management Development and Productivity Institute',
  'MDPI': 'Management Development and Productivity Institute',
  'MLJE/Management Development and Productivity Institute': 'Management Development and Productivity Institute',
  'MASLOC': 'Microfinance and Small Loans Centre (MASLOC)',
  'Mest': 'Ministry of Environment, Science and Technology',
  'MINISTRY OF ENVIRONMENT SCIENCE AND TECHNOLOGY': 'Ministry of Environment, Science and Technology',
  'Ministry of environment science and technology': 'Ministry of Environment, Science and Technology',
  'Ministry of Environment, Science and Technology': 'Ministry of Environment, Science and Technology',
  'MiDA': 'Millennium Development Authority (MiDA)',
  'Millennium Development Authority': 'Millennium Development Authority (MiDA)',
  'Min of Gender, Children and Social Protection': 'Ministry of Gender, Children and Social Protection',
  'Ministry of Gender': 'Ministry of Gender, Children and Social Protection',
  'Ministry of Gender Children and Social Protection': 'Ministry of Gender, Children and Social Protection',
  'Ministry of Gender, Children and Social Protection': 'Ministry of Gender, Children and Social Protection',
  'MoGCSP': 'Ministry of Gender, Children and Social Protection',
  'Min. Of Food and Agric': 'Ministry of Food and Agriculture',
  'Ministry of food and Agriculture': 'Ministry of Food and Agriculture',
  'Ministry of Food and Agriculture': 'Ministry of Food and Agriculture',
  'MOFA': 'Ministry of Food and Agriculture',
  'MIN. OF TOURISM CULTURE AND CREATIVE ARTS': 'Ministry of Tourism, Culture and Creative Arts',
  'Ministry of Tourism Culture and Creative Arts': 'Ministry of Tourism, Culture and Creative Arts',
  'Ministry of tourism culture and creative arts': 'Ministry of Tourism, Culture and Creative Arts',
  'Ministry of Tourism, Culture and Creative Arts': 'Ministry of Tourism, Culture and Creative Arts',
  'Ministry of Tourism/HOTCATT': 'Ministry of Tourism, Culture and Creative Arts',
  'Minerals Commission': 'Minerals Commission',
  'Minerals commission': 'Minerals Commission',
  'Ministry of Affairs': 'Ministry of Foreign Affairs and Regional Integration',
  'Ministry of Foreign': 'Ministry of Foreign Affairs and Regional Integration',
  'Ministry of Foreign Affairs': 'Ministry of Foreign Affairs and Regional Integration',
  'Ministry of Communication, Digital Technology and communications': 'Ministry of Communications, Digital Technology and Innovations',
  'Ministry of Communication, digital technology and innovations': 'Ministry of Communications, Digital Technology and Innovations',
  'Ministry of Communication, Digital Technology and Innovations': 'Ministry of Communications, Digital Technology and Innovations',
  'Ministry of Communications Digital Technology and Innovations': 'Ministry of Communications, Digital Technology and Innovations',
  'MoCDTI': 'Ministry of Communications, Digital Technology and Innovations',
  'MOCDTI': 'Ministry of Communications, Digital Technology and Innovations',
  'Ministry of Defence': 'Ministry of Defence',
  'MoD': 'Ministry of Defence',
  'Ministry of Education': 'Ministry of Education',
  'Ministry of Education ( Ghana TVETS)': 'Ministry of Education',
  'Ministry of Education(Ghana TVET)': 'Ministry of Education',
  'Ministry of Energy': 'Ministry of Energy',
  'Ministry of Energy and Green Transition': 'Ministry of Energy and Green Transition',
  'Ministry of Finance': 'Ministry of Finance',
  'Ministry of finance': 'Ministry of Finance',
  'MoF': 'Ministry of Finance',
  'Ministry of Fisheries': 'Ministry of Fisheries &Aqua-Culture Development',
  'Ministry of Fisheries and Aquaculture': 'Ministry of Fisheries &Aqua-Culture Development',
  'MINISTRY OF FISHERIES AND AQUACULTURE': 'Ministry of Fisheries &Aqua-Culture Development',
  'Ministry of Fisheries and aquaculture': 'Ministry of Fisheries &Aqua-Culture Development',
  'Ministry of Labour Jobs and Employment': 'Ministry of Labour, Jobs and Employment',
  'Ministry of Labour, Jobs and Employment': 'Ministry of Labour, Jobs and Employment',
  'MINISTRY OF LABOUR, JOBS AND EMPLOYMENT': 'Ministry of Labour, Jobs and Employment',
  'MLJE': 'Ministry of Labour, Jobs and Employment',
  'Ministry of Local Government, Chieftaincy and Religious Affairs': 'Ministry of Local Government, Chieftaincy and Religious Affairs',
  'Ministry of local government,Chieftaincy and Religious Affairs': 'Ministry of Local Government, Chieftaincy and Religious Affairs',
  'Ministry of Roads and Highways': 'Ministry of Roads and Highways',
  'MINISTRY OF ROADS AND HIGHWAYS': 'Ministry of Roads and Highways',
  'Ministry of Roads and Highways, Koforidua Training Centre': 'Ministry of Roads and Highways',
  'MRH': 'Ministry of Roads and Highways',
  'Ministry of Sports and Recreation': 'Ministry of Sports and Recreation',
  'Ministry of the Interior': 'Ministry of the Interior',
  'MINISTRY OF THE INTERIOR': 'Ministry of the Interior',
  'MINISTRY OF THE INTERIOR / NARCOTICS CONTROL COMMISSION': 'Narcotics Control Commission',
  'Ministry of the Interior/ Narcotics Control Commission': 'Narcotics Control Commission',
  'Narcotics Control Commission': 'Narcotics Control Commission',
  'Ministry of Trade Agribusiness and Industry': 'Ministry of Trade, Agribusiness and Industry',
  'Ministry of Trade, Agribusiness and Industry': 'Ministry of Trade, Agribusiness and Industry',
  'Ministry of Transpo': 'Ministry of Transport',
  'Ministry of Transport': 'Ministry of Transport',
  'Ministry of Youth Development and Empowerment': 'Ministry of Youth Development and Empowerment',
  'Ministry of youth development and empowerment': 'Ministry of Youth Development and Empowerment',
  'MYDE': 'Ministry of Youth Development and Empowerment',
  'NaCCA': 'National Council for Curriculum and Assessment',
  'National Council for Curriculum and Assessment': 'National Council for Curriculum and Assessment',
  'NADMO': 'National Disaster Management Organisation (NADMO)',
  'National Disaster Management Organisation': 'National Disaster Management Organisation (NADMO)',
  'NATIONAL DISASTER MANAGEMENT ORGANIZATION': 'National Disaster Management Organisation (NADMO)',
  'National Disaster Management organization': 'National Disaster Management Organisation (NADMO)',
  'National Biosafety Authority': 'National Biosafety Authority',
  'NATIONAL BIOSAFETY AUTHORITY': 'National Biosafety Authority',
  'National Commission on Culture': 'National Commission on Culture',
  'National Commission on Culture Accra': 'National Commission on Culture',
  'NATIONAL COMMISSION ON SMALL ARMS AND LIGHT WEAPONS': 'National Commission on Small Arms and Light Weapons',
  'National Commission on Small Arms and Light Weapons': 'National Commission on Small Arms and Light Weapons',
  'Small arms': 'National Commission on Small Arms and Light Weapons',
  'National Communications Authority (NCA)': 'National Communications Authority (NCA)',
  'NCA': 'National Communications Authority (NCA)',
  'National Council on Person with Disability': 'National Council on Persons with Disability',
  'NATIONAL COUNCIL ON PERSONS WITH DISABILITY': 'National Council on Persons with Disability',
  'National Council on Persons with Disability': 'National Council on Persons with Disability',
  'National council on persons with disability': 'National Council on Persons with Disability',
  'NATIONAL DEVELOPMENT PLANNING COMMISSION': 'National Development Planning Commission',
  'National Development Planning Commission': 'National Development Planning Commission',
  'NDPC': 'National Development Planning Commission',
  'National Health Insurance - Juaboso District': 'National Health Insurance Authority (NHIA)',
  'NATIONAL HEALTH INSURANCE AUTHORITY': 'National Health Insurance Authority (NHIA)',
  'National Health Insurance Authority': 'National Health Insurance Authority (NHIA)',
  'National Health Insurance Authority Bia': 'National Health Insurance Authority (NHIA)',
  'National Health Insurance Authority,': 'National Health Insurance Authority (NHIA)',
  'NHIA': 'National Health Insurance Authority (NHIA)',
  'NATIONAL IDENTIFICATIOIN AUTHORITY': 'National Identification Authority',
  'National Identification Authority': 'National Identification Authority',
  'NIA': 'National Identification Authority',
  'National information Technology Agency': 'National Information Technology Agency',
  'National Population Council': 'National Population Council',
  'NPC': 'National Population Council',
  'National Premix Fuel Secretariat': 'National Premix Fuel Secretariat',
  'National Premix Fuel Secretriat': 'National Premix Fuel Secretariat',
  'National Road Safety Authority': 'National Road Safety Authority',
  'NRA': 'National Road Safety Authority',
  'National Schools Inspectorate Authority': 'National Schools Inspectorate Authority',
  'NATIONAL SCHOOLS INSPECTORATE AUTHORITY': 'National Schools Inspectorate Authority',
  'National Sports Authority': 'National Sports Authority',
  'National sports Authority': 'National Sports Authority',
  'National Teaching Council': 'National Teaching Council',
  'NTC': 'National Teaching Council',
  'National theatre of Ghana': 'National Theatre of Ghana',
  'National Theatre of ghana': 'National Theatre of Ghana',
  'Abibigromma': 'National Theatre of Ghana',
  'National Youth Authority': 'National Youth Authority',
  'National YouthAuthority': 'National Youth Authority',
  'NYA': 'National Youth Authority',
  'Northern Development Authority': 'Northern Development Authority',
  'NORTHERN DEVELOPMENT AUTHORITY': 'Northern Development Authority',
  'OGM/Northern Development Authority': 'Northern Development Authority',
  'Northern Regional Coordinating Council': 'Northern Regional Coordinating Council',
  'NRCC': 'Northern Regional Coordinating Council',
  'Nursing and Midwifery Council': 'Nursing and Midwifery Council',
  'NURSING AND MIDWIFERY COUNCIL OF GHANA': 'Nursing and Midwifery Council',
  'Office of the Administrator General': 'Office of the Administrator-General',
  'Office of the Administrator-General': 'Office of the Administrator-General',
  'Office of the Attorney General and Ministry of Justice': 'Office of the Attorney General and Ministry of Justice',
  'Office of the Attorney-General and Ministry of Justice': 'Office of the Attorney General and Ministry of Justice',
  'Office of the Government Machinery': 'Office of Government Machinery',
  'OGM': 'Office of Government Machinery',
  'OGM/ISD': 'Information Services Department',
  'Office of the head of Civil Service': 'Office of the Head of Civil Service',
  'Office of the Head of Civil Service': 'Office of the Head of Civil Service',
  'Office of the Head of the Civil Service': 'Office of the Head of Civil Service',
  'OHCS': 'Office of the Head of Civil Service',
  'Office of the Head of Local Government Service': 'Office of the Head of Local Government Service',
  'Office of the Head of the Local Government Service': 'Office of the Head of Local Government Service',
  'OHLGS': 'Office of the Head of Local Government Service',
  'Office of the Registrar of Companies': 'Office of the Registrar of Companies',
  'Office of the Registrar of companies': 'Office of the Registrar of Companies',
  'OFFICE OF THE REGISTRAR OF COMPANIES': 'Office of the Registrar of Companies',
  "Registrar-General's Department": 'Office of the Registrar of Companies',
  'Office of the special prosecutor': 'Office of The Special Prosecutor',
  'Office of the Special Prosecutor': 'Office of The Special Prosecutor',
  'Public Sector Reform Secretariat': 'Public Sector Reform Secretariat',
  'Public Sector Reform Secretariat (Office of the President)': 'Public Sector Reform Secretariat',
  'Public Services Commission': 'Public Services Commission',
  'Right to information Commission': 'Right to Information Commission',
  'Savannah Regional Coordinating Council': 'Savannah Regional Coordinating Council',
  'SRCC': 'Savannah Regional Coordinating Council',
  'Volta RCC': 'Volta Regional Coordinating Council',
  'VRCC': 'Volta Regional Coordinating Council',
  'YUNYOO-NASUAN DISTRICT ASSEMBLY': 'Yunyoo Nasuan District',
  'Zongo and Inner City Dev.Secretariat-OOP': 'Zongo and Inner-City Development Secretariat',
  'Zongo and Inner-Cities Development Secretariat (OGM)': 'Zongo and Inner-City Development Secretariat',
  'Zongo and Inner-City Development Secretariat': 'Zongo and Inner-City Development Secretariat',
  'Zongo and Inner-City Development Secretariat (OGM)': 'Zongo and Inner-City Development Secretariat',
  'Zongo and Inner-City Development Secretariat-Office of the President': 'Zongo and Inner-City Development Secretariat',
  'Legal Aid Commission': 'Legal Aid Commission',
  'Audit Service': 'Audit Service',
};

// Reuse an institution ID/name/type already in Firestore instead of
// slugifying the canonical name into a brand new institution. Anything not
// listed here defaults to { id: slugify(canonicalName), type: 'MDA' }.
const CANONICAL_META = {
  'Ministry of Defence': { id: 'ministry-of-defence', name: 'Ministry of Defence' },
  'Ministry of Education': { id: 'ministry-of-education', name: 'Ministry of Education' },
  'Ministry of Labour, Jobs and Employment': { id: 'ministry-of-employment-and-labour-relations', name: 'Ministry of Labour, Jobs and Employment' },
  'Ministry of Energy': { id: 'ministry-of-energy', name: 'Ministry of Energy' },
  'Ministry of Environment, Science and Technology': { id: 'ministry-of-environment-science-technology-and-innovation', name: 'Ministry of Environment, Science Technology and Innovation' },
  'Ministry of Finance': { id: 'ministry-of-finance', name: 'Ministry of Finance' },
  'Ministry of Fisheries &Aqua-Culture Development': { id: 'ministry-of-fisheries-aqua-culture-development', name: 'Ministry of Fisheries &Aqua-Culture Development' },
  'Ministry of Food and Agriculture': { id: 'ministry-of-food-and-agriculture', name: 'Ministry of Food and Agriculture' },
  'Ministry of Foreign Affairs and Regional Integration': { id: 'ministry-of-foreign-affairs-and-regional-integration', name: 'Ministry of Foreign Affairs and Regional Integration' },
  'Ministry of Gender, Children and Social Protection': { id: 'ministry-of-gender-children-and-social-protection', name: 'Ministry of Gender, Children and Social Protection' },
  'Ministry of Lands and Natural Resources': { id: 'ministry-of-lands-and-natural-resources', name: 'Ministry of Lands and Natural Resources' },
  'Ministry of Local Government, Chieftaincy and Religious Affairs': { id: 'ministry-of-local-government', name: 'Ministry of Local Government, Chieftaincy and Religious Affairs' },
  'Ministry of Roads and Highways': { id: 'ministry-of-roads-and-highways', name: 'Ministry of Roads and Highways' },
  'Ministry of the Interior': { id: 'ministry-of-the-interior', name: 'Ministry of the Interior' },
  'Ministry of Tourism, Culture and Creative Arts': { id: 'ministry-of-tourism-culture-and-creative-arts', name: 'Ministry of Tourism, Culture and Creative Arts' },
  'Ministry of Trade, Agribusiness and Industry': { id: 'ministry-of-trade-and-industry', name: 'Ministry of Trade, Agribusiness and Industry' },
  'Ministry of Transport': { id: 'ministry-of-transport', name: 'Ministry of Transport' },
  'Ministry of Youth Development and Empowerment': { id: 'ministry-of-youth-development-and-empowerment', name: 'Ministry of Youth Development and Empowerment' },
  'National Development Planning Commission': { id: 'national-development-planning-commission', name: 'National Development Planning Commission' },
  'National Media Commission': { id: 'national-media-commission', name: 'National Media Commission' },
  'Office of Government Machinery': { id: 'office-of-government-machinery', name: 'Office of Government Machinery' },
  'Office of the Attorney General and Ministry of Justice': { id: 'office-of-the-attorney-general-and-ministry-of-justice', name: 'Office of the Attorney General and Ministry of Justice' },
  'Office of the Head of Civil Service': { id: 'office-of-the-head-of-civil-service', name: 'Office of the Head of Civil Service' },
  'Office of The Special Prosecutor': { id: 'office-of-the-special-prosecutor', name: 'Office of The Special Prosecutor' },
  'Public Services Commission': { id: 'public-services-commission', name: 'Public Services Commission' },
  'Right to Information Commission': { id: 'right-to-information-commission', name: 'Right to Information Commission' },
  'Legal Aid Commission': { id: 'legal-aid-commission', name: 'Legal Aid Commission' },
  'Audit Service': { id: 'audit-service', name: 'Audit Service' },
  'Commission on Human Rights and Administrative Justice': { id: 'commission-on-human-rights-and-administrative-justice', name: 'Commission on Human Rights and Administrative Justice' },
  'Yunyoo Nasuan District': { id: 'yunyoo-nasuan-district', name: 'Yunyoo Nasuan District', type: 'MMDA' },
};

// RAW_ALIASES keys are written with natural casing for readability, but
// lookups happen against a normalized (lowercased/whitespace-collapsed)
// string — so the lookup table itself must be pre-normalized too, otherwise
// e.g. "MLNR" (normalized to "mlnr") would never match the "MLNR" key.
const ALIASES = {};
for (const [raw, canonical] of Object.entries(RAW_ALIASES)) {
  ALIASES[norm(raw)] = canonical;
}

module.exports = { ALIASES, CANONICAL_META, norm };
